---
- name: install httpd
  hosts: node1.example.com

  tasks:
  - name: install httpd 
    yum:     
      name: httpd          
      state: present

  - name: ensure https is running
    service:
      name: httpd
      state: started
      enabled: true

  - name: create index file
    copy:
      dest: "/var/www/html/index.html"
      content: "Welcome to my web server \n"

  - name: enable firewall
    service:
      name: firewalld
      state: started
      enabled: true
 
  - name: open http port
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
...
